### ISSUE TITLE
Coordinates near Hungary/Romania border (on Hungary side) return no timezone

### ISSUE THREAD

**Issue by joaocanaverde** [RomanIakovlev/timeshape#120]
# Wrong or unexpected timezone is returned
Coordinates near Hungary/Romania border (on Hungary side) return no timezone.

## Which Timeshape version are you using?
2022g.17

## Which Java version are you using?
18.0.2

## If you upgrade to the latest Java minor version, does it still fail?
  * Yes 
    - 18.0.2

## Which coordinates are you using?
46.16799, 20.71524

## Which timezone is returned?
`None`

## Which timezone is expected?
`Europe/Budapest`

## Additional information
This is very close to the border with Romania, but still in Hungary:

https://www.google.com/maps/place/46°10'04.8%22N+20°42'54.9%22E/@46.16799,20.7130513,17z/data=!3m1!4b1!4m4!3m3!8m2!3d46.16799!4d20.71524

**Comment by RomanIakovlev** [comment]
Thanks for reporting this, I'll have a look. From the first glance it looks like the problem with the source data, so it might be worth checking this with the https://github.com/evansiroky/timezone-boundary-builder.

**Comment by evansiroky** [comment]
Hello. I'm the maintainer of timezone-boundary-builder. This particular coordinate is so close to being exactly on the border of data from OpenStreetMap which is the data source of timezone-boundary-builder. I'm attaching a screenshot of this coordinate as it appears on OpenStreetMap:

<img width="796" alt="Screen Shot 2023-07-20 at 3 47 44 PM" src="https://github.com/RomanIakovlev/timeshape/assets/3112493/0b56239a-290d-4c7b-bfe7-1c65e76d93f8">

I tried this coordinate out with [timezonefinder](https://timezonefinder.michelfe.it/gui/0_20.71524_46.16799) and [node-geo-tz](https://www.npmjs.com/package/geo-tz) and both of them are returning `Europe/Budapest`.

**Comment by lavika11** [comment]
I think the problem occurs because of the use of the "GeometryEngine.contains" method in the Index class. https://github.com/RomanIakovlev/timeshape/blob/a170d21fffb99b0727aa00a48871f1588afc7df4/core/src/main/java/net/iakovlev/timeshape/Index.java#L51
In the documentation, the "Contains" relation is described as follows: "One geometry contains another geometry if the other geometry is a subset of it and their insides have at least one point in common". http://esri.github.io/geometry-api-java/doc/Contains.html
In this particular case, the point is on the boundary of the zone, so the interior of the zone has no points in common with the point, only the boundary. So the point is not contained within the zone, and the "contains" method returns false if it checks if 
the point is contained in the zone. I suppose it would be better to use "intersects" instead of "contains", as this will cover cases where the point belongs to either the boundary or the interior of the zone.

**Comment by RomanIakovlev** [comment]
Nice find @lavika11! `Contains` is most probably the culprit, given the description from the docs. Would you mind taking a stab at making the necessary change, so that Timeshape can support both internal and border point queries?

P.S. it's probably worth noting Timeshape also uses `contains` in a couple of other places, particularly in `Index::queryPolyline` method, which should be updated too.

**Comment by lavika11** [comment]
Yes, I an take a look.

**Comment by RomanIakovlev** [comment]
This should be fixed in Timeshape version 2023b.19 thanks to contribution from @lavika11. @joaocanaverde please give it a try and feel free to reopen the issue if the problem persists.
