### ISSUE TITLE
Asia/Qostanay time zone is missing

### ISSUE THREAD

**Issue by tariver** [RomanIakovlev/timeshape#47]
Asia/Qostanay time zone was added in [2018h](https://mm.icann.org/pipermail/tz-announce/2018-December/000053.html), but not in the list of timezones received by this function
```
this.engine.getKnownZoneIds();
```

Also when queried with coordinates of Qostanay the following function returns an empty list
```
private final TimeZoneEngine engine;
    
private TimeZoneService() {
  this.engine = TimeZoneEngine.initialize();
}
  
public List<ZoneId> findZoneIds(53.205415658681055, 63.646202087402344) {
  return engine.queryAll(lat, lng);
}
```

**Comment by RomanIakovlev** [comment]
Asia/Qostanay is included into Timeshape starting from version 2019b.7, but you need an up-to-date version of JRE to be able to use it, since Timeshape works with instances of `java.time.ZoneId`, and those are defined by JRE. Based on my quick analysis, it seems Asia/Qostanay is first included in following JREs: 12.0.2, 11.0.4, 8u221, 7u231. If you use anything older than that, Timeshape will log an error during initalization:

`Some of the zone ids were not recognized by the Java runtime and will be ignored. The most probable reason for this is outdated Java runtime version. The following zones were not recognized: Asia/Qostanay`
(this is what it prints on my JRE 8u171).

If you use up to date versions of Timeshape and JRE and still get this issue, please let me know the actual versions of Timeshape and JRE you use, and I'll have a deeper look.

**Comment by tariver** [comment]
> Timeshape works with instances of `java.time.ZoneId`, and those are defined by JRE

ОК, thanks for the clarifying, I thought you used "in-house" list.

> Based on my quick analysis, it seems Asia/Qostanay is first included in following JREs: 12.0.2, 11.0.4, 8u221, 7u231.

You don't need to update the whole JRE, just the tzdata of it using [Oracle's utility "Timezone Updater Tool"](https://www.oracle.com/technetwork/java/javase/tzupdater-readme-136440.html).

Just for the purpose if someone else google this up, a quick guide
[Download](https://www.oracle.com/technetwork/java/javase/downloads/tzupdater-download-513681.html) and unzip the file
Useful commands:
`java -jar tzupdater.jar` - update to latest available version
`java -jar tzupdater.jar -V` - displays current version of JRE's tzdata
`java -jar tzupdater.jar -l https://data.iana.org/time-zones/releases/tzdata2019b.tar.gz -v` update to certain version. All can be found [here](https://data.iana.org/time-zones/releases/).

After updating JRE 8u131 with this tool to 2019b everything works fine. Thanks again for the help!

**Comment by RomanIakovlev** [comment]
Great you mentioned the timezone updater tool, I have totally forgotten about it, and good to know everything works for you now.
On an unrelated note, I'm really interested in how different people and companies use Timeshape. Could you please share a bit, what's your use case? Do you use it for some analytics, GPS tracks processing, or something else?

**Comment by tariver** [comment]
> On an unrelated note, I'm really interested in how different people and companies use Timeshape. Could you please share a bit, what's your use case? Do you use it for some analytics, GPS tracks processing, or something else?

We use it in our in-house application that deploys (clones) the system that we develop. Since it's a GIS system, the deploying applications needs to know at which area it will be focused and the timezone there. So a user on a map chooses a zone which the deployed system will cover and the deploying application determines which timezone will be used based on the center of the area selected by user.

**Comment by RomanIakovlev** [comment]
Cool, thanks for sharing! It would be nice if you could add your company to the readme (https://github.com/RomanIakovlev/timeshape#adopters). I know there are quite a bit of companies out there using Timeshape (judging by the number of downloads from Maven Central), and it would be fair to have this reflected on the main page. 

(Of course, only if you feel comfortable doing so. But if it's possible, just send a pull request to the README.MD file.)
