### ISSUE TITLE
Initialize with TarArchiveInputStream

### ISSUE THREAD

**Issue by jnickels** [RomanIakovlev/timeshape#53]
Hi @RomanIakovlev,
I really like your project! Thanks for the great work!
Since a couple of hours I try to initialize your TimeZoneEngine with data generated by your builder module. The builder module works just fine. At least the output is a ~20MB file (input was timezones-with-oceans.geojson.zip 2019b). But when I try to initialize TimeZoneEngine with TarArchiveInputStream(FileInputStream("file.zip")) I always receive a error:
```
Error detected parsing the header
Invalid byte 110 at offset 0 in 'n���Fg&' len=8
```
Any idea or recommendation? I already tried it with Java 1.8 and 11. Also on Win and Mac. :-/

**Comment by RomanIakovlev** [comment]
Hi @jnickels, and thanks for your kind words! I appreciate you enjoy using Timeshape, and, as a side note, I would love to hear what kind of application/service you build with it.

Regarding your problem, it's quite difficult to pinpoint what's going on. I presume you're calling this function: `public static TimeZoneEngine initialize(TarArchiveInputStream f)`. One possible thing would be that you don't decompress the file first. Builder module produces the Tar archive compressed with Zstd algorithm, and to read it in the main module, you need to decompress the Tar first. The javadoc of this function gives an example of how to call it:
```
try (InputStream resourceAsStream = new FileInputStream("./core/target/resource_managed/main/data.tar.zstd");
     TarArchiveInputStream f = new TarArchiveInputStream(new ZstdCompressorInputStream(resourceAsStream))) {
        engine = TimeZoneEngine.initialize(f);
    } catch (NullPointerException | IOException e) {
        throw new RuntimeException(e);
    }
```
Here the `ZstdCompressorInputStream` is first used to decompress the file, and then the `TarArchiveInputStream` is used to read the archive contents.

If you do this and it still doesn't work, maybe you could prepare a minimal reproducible example, so that I could have a deeper look?

**Comment by RomanIakovlev** [comment]
Hi @jnickels, were you able to solve this problem? I'm curious if there's anything in Timeshape that doesn't play well with initializing from file, but if there's nothing to fix here, I'd rather close this issue.

**Comment by RomanIakovlev** [comment]
This is probably solved by now, so I'll just go ahead and close this issue. Please feel free to open another one if you see this problem again.
